linters-settings:
    errcheck:
        check-type-assertions: false
        check-blank: false
    govet:
        check-shadowing: true
    golint:
        min-confidence: 0 # 0.8
    gocyclo:
        min-complexity: 12 # 30
    maligned:
        suggest-new: false
    dupl:
        threshold: 150
    goconst:
        min-len: 3
        min-occurrences: 3
    unused:
        check-exported: false
    unparam:
        algo: cha
        check-exported: false
    nakedret:
        max-func-lines: 30
    prealloc:
        simple: true
        range-loops: true
        for-loops: false
    gocritic:
        enabled-checks:
            - appendAssign
            - appendCombine
            - assignOp
            - boolExprSimplify
            - caseOrder
            - defaultCaseOrder
            - deprecatedComment
            - dupArg
            - dupBranchBody
            - dupCase
            - flagDeref
            - ifElseChain
            - indexAlloc
            - methodExprCall
            - rangeExprCopy
            # - rangeValCopy
            - regexpMust
            - singleCaseSwitch
            - sloppyLen
            # - switchTrue
            - typeSwitchVar
            - underef
            # - unlabelStmt
            - unlambda
            - unslice

linters:
    enable-all: true
    disable:
        - gofmt
        - goimports
        - depguard
        - dupl
        - lll

issues:
    exclude-use-default: false
    exclude:
        - "should have a package comment"
        - "G104: Errors unhandled"
        - "G204: Subprocess launched with variable"
        - "G304: Potential file inclusion via variable"
        - "G402: TLS `InsecureSkipVerify` set true"
        - "Error return value of `(os\\.(Un)?Setenv|.*\\.Close)` is not checked"
