version: 2.1

jobs:
    test:
        docker:
            - image: "cimg/go:1.15"
              environment:
                GOFLAGS: "-mod=readonly"
                GOLANGCI_LINT_VER:  1.24.0
        steps:
            - checkout
            - run: env | grep _VER | sort > /tmp/tools.ver
            - restore_cache:
                keys:
                    - v3-{{ checksum "/tmp/tools.ver" }}-{{ checksum "go.mod" }}-{{ .Branch }}
                    - v3-{{ checksum "/tmp/tools.ver" }}-{{ checksum "go.mod" }}-
                    - v3-{{ checksum "/tmp/tools.ver" }}-
            - run:
                name: Install tools
                command: |
                    cd /
                    golangci-lint --version | tee /dev/stderr | grep -wq $GOLANGCI_LINT_VER ||
                        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v$GOLANGCI_LINT_VER
                    go get -v github.com/mattn/goveralls
            - run: go mod download
            - run: golangci-lint run
            - run: gotestsum -- -race ./...
            - run: test -z "$COVERALLS_TOKEN" || goveralls -service=circle-ci
            - save_cache:
                when: always
                key: v3-{{ checksum "/tmp/tools.ver" }}-{{ checksum "go.mod" }}-{{ .Branch }}
                paths:
                    - ~/go/bin/
                    - ~/go/pkg/
                    - ~/go/src/
                    - ~/.cache/go-build/
                    - ~/.cache/golangci-lint/

    release:
        docker:
            - image: "cimg/go:1.15"
              environment:
                GOFLAGS: "-mod=readonly"
                GHR_VER: 0.13.0
        steps:
            - checkout
            - run: echo -e "$GPG_KEY" | gpg --import
            - run:
                name: Install tools
                command: |
                    curl -sfL https://github.com/tcnksm/ghr/releases/download/v${GHR_VER}/ghr_v${GHR_VER}_linux_amd64.tar.gz |
                        tar xzf - -C /tmp && mv /tmp/ghr_v${GHR_VER}_linux_amd64/ghr /go/bin/
            - run: ./release

workflows:
    test-and-release:
        jobs:
            - test:
                filters:
                    tags:
                        only: /v.*/
            - release:
                requires:
                    - test
                filters:
                    tags:
                        only: /v.*/
                    branches:
                        ignore: /.*/
