#!/bin/bash
export PATH="$PWD/.buildcache/bin:$PATH"
set -e -o pipefail
go generate 0-tools.go

gotestsum -- \
    -coverpkg="$(go list ./... | paste -s -d,)" \
    -coverprofile .buildcache/cover.out \
    "$@" ./...

go tool cover -func=.buildcache/cover.out | tail -n 1 | xargs echo

test -n "$CI" || go tool cover -html=.buildcache/cover.out
