#!/bin/bash
export PATH="$PWD/.gobincache:$PATH"
set -x -e -o pipefail
go generate

DIST_DIR=bin
TAG=$(git describe --match='v*' --exact-match --tags)
GH="$(git remote get-url origin | sed -e 's/.*://' -e 's/\.git$//')"
GH_USER="${GH%%/*}"
GH_REPO="${GH##*/}"

mkdir -p $DIST_DIR
while read -r suffix GOOS GOARCH GOARM; do
	CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH GOARM=$GOARM \
		go build -o "$DIST_DIR/${GH_REPO}-$suffix" -ldflags "-X 'main.ver=$TAG'"
	pushd "$DIST_DIR"
	sha256sum "${GH_REPO}-$suffix" > "${GH_REPO}-$suffix.sha256"
	#gpg --armor --output "${GH_REPO}-$suffix.asc" --detach-sign "${GH_REPO}-$suffix"
	popd
done <<DIST
linux-x86_64            linux   amd64
linux-386               linux   386
linux-armel             linux   arm     5
linux-armhf             linux   arm     6
linux-arm64             linux   arm64
linux-ppc64le           linux   ppc64le
linux-s390x             linux   s390x
linux-mips64            linux   mips64le
linux-riscv64           linux   riscv64
darwin-x86_64           darwin  amd64
darwin-arm64            darwin  arm64
DIST

ghr -u "$GH_USER" -r "$GH_REPO" -replace "$TAG" "$DIST_DIR"
