name: Dependency review

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  main:
    uses: powerman/.github/.github/workflows/dependency-review.yml@main
    secrets: inherit
